pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/HarshaMantrodi/Jenkins-servers.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t jenkins-servers .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh '''
                docker stop jenkins-servers-app || true
                docker rm jenkins-servers-app || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d --name jenkins-servers-app -p 3000:3000 jenkins-servers'
            }
        }
    }
}

